import Foundation
import NeechanCore
import Testing
@testable import Neechan

/// The watcher's background task identifier, which is written down twice.
///
/// `BGTaskScheduler.register` does not return a failure when handed an
/// identifier the app's `Info.plist` does not permit — it raises, during launch,
/// before anything is on screen. So the Swift constant and the plist entry are a
/// pair that cannot come apart quietly, and nothing else checks them: the plist
/// half is generated by XcodeGen from `project.yml`, so the two are not even
/// edited in the same file.
@Suite("Background task identifier")
struct BackgroundTaskIdentifierTests {
    private var permitted: [String] {
        Bundle.main.object(
            forInfoDictionaryKey: "BGTaskSchedulerPermittedIdentifiers"
        ) as? [String] ?? []
    }

    @Test("the identifier the app registers is one the Info.plist permits")
    func identifierIsPermitted() {
        #expect(
            permitted.contains(BackgroundRefresh.taskIdentifier),
            """
            BackgroundRefresh.taskIdentifier is \(BackgroundRefresh.taskIdentifier), \
            which BGTaskSchedulerPermittedIdentifiers does not list \
            (it lists \(permitted)). Registering it would raise on launch.
            """
        )
    }

    /// The app registers one task and declares one. A second entry would be
    /// something nothing registers, which is the other way these drift.
    @Test("nothing is permitted that the app does not register")
    func nothingIsPermittedInVain() {
        #expect(permitted == [BackgroundRefresh.taskIdentifier])
    }

    /// Not a rule Apple enforces, but the reason the identifier reads the way it
    /// does: it is the app's own, so it is named after the app.
    @Test("the identifier is namespaced under the app")
    func identifierIsNamespaced() {
        #expect(BackgroundRefresh.taskIdentifier.hasPrefix("pro.neechan.app"))
    }
}
